[package]
name = "rosu-np-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "rosu_np_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"
